### ISSUE TITLE
When no target markets are selected the country drop down shows empty

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1255] opened 2014-05-03 20:34 UTC
This on checkout pages isn't helpful.

Perhaps an admin nag to select something, and on the checkout page something more useful than an empty drop down select

**Comment by JustinSainton** [comment] 2015-06-12 05:11
Duplicate of #711

**Closed by JustinSainton** 2015-06-12 05:11 UTC
