### ISSUE TITLE
Taxes stopped being charged in 3.9.1

### ISSUE THREAD

**Issue by Bloke1** [wp-e-commerce/WP-e-Commerce#1757] opened 2015-01-30 15:11 UTC
After upgrading to version 3.9.1 the taxes stopped being charged. I have these settings.
1. Product prices are tax exclusive
2. Apply tax when shipping is same as tax rate.

If I have the check box to tax shipping it will charge tax but of course tax the shipping also. If I don't tax the shipping it does not charge any taxes at all.

**Comment by misulicus** [comment] 2015-01-30 15:12
Is there a store URL where we can check ?

**Comment by Bloke1** [comment] 2015-02-02 20:16
Yes but you can't see anything unless you are logged in. I can't post the URL here because I don't like it showing in search engine results.

**Comment by Bloke1** [comment] 2015-02-02 20:19
Do this show the URL online. Just testing.

**Comment by JustinSainton** [comment] 2015-02-02 20:22
HI @Bloke1,

This may be a duplicate of #1712.

Do you want to try applying 1b45c7ba40234b9e34b1c9db673e35ce1b23518d and see if that resolves your issue?

**Comment by Bloke1** [comment] 2015-02-02 21:54
Would I just replace that file?

**Comment by JustinSainton** [comment] 2015-02-02 21:55
Yep, you could do a full replace with this file --> https://raw.githubusercontent.com/wp-e-commerce/WP-e-Commerce/1b45c7ba40234b9e34b1c9db673e35ce1b23518d/wpsc-taxes/controllers/taxes_controller.class.php

**Comment by Bloke1** [comment] 2015-02-03 18:10
Thanks that fixed it.

**Closed** 2015-04-04 02:44 UTC

**Comment by rsgourley** [comment] 2017-06-12 13:34
I was hoping this would solve a problem I'm having, but it didn't. We're charging tax when the shipping address is in CA, but it is not working when the user checks the 'Same as billing address:' box instead of entering the address again.  Any tips? The site is http://easternclassics.net
