### ISSUE TITLE
Coupons Can be Active but determined to be invalid

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#2039] opened 2016-01-07 13:45 UTC
Coupon class is_valid() method checks to see if coupon is used. If it is uses it is determined to be invalid.

A used coupon can be inactive due to the use once setting, then manually re-activated. 

When this happens the coupon can not be applied to a cart

**Comment by benhuson** [comment] 2016-02-04 13:30
Closing - I think this is a duplicate of #1739 - see the comments there.

I still think as per my comment in that thread that you should be able to re-enable a single-use coupon if you want to.

**Closed by benhuson** 2016-02-04 13:30 UTC
