### ISSUE TITLE
WP-eCommerce News Dashboard Widget Causing php error

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1776] opened 2015-03-03 15:46 UTC
[03-Mar-2015 15:45:14 UTC] 
error type: [2048] call_user_func_array() expects parameter 1 to be a valid callback, non-static method WP_Feed_Cache::create() should not be called statically file: D:\web-site-dev\pyebrook.com\wp-includes\SimplePie\Registry.php line: 215

**Comment by JeffPyeBrook** [comment] 2015-03-03 15:50
This is a more complete stack trace
```
[03-Mar-2015 15:48:43 UTC] PHP Strict standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method WP_Feed_Cache::create() should not be called statically in D:\web-site-dev\pyebrook.com\wp-includes\SimplePie\Registry.php on line 215

[03-Mar-2015 15:48:43 UTC] PHP Stack trace:

[03-Mar-2015 15:48:43 UTC] PHP   1. {main}() D:\web-site-dev\pyebrook.com\wp-admin\index.php:0

[03-Mar-2015 15:48:43 UTC] PHP   2. wp_dashboard() D:\web-site-dev\pyebrook.com\wp-admin\index.php:126

[03-Mar-2015 15:48:43 UTC] PHP   3. do_meta_boxes($screen = *uninitialized*, $context = *uninitialized*, $object = *uninitialized*) D:\web-site-dev\pyebrook.com\wp-admin\includes\dashboard.php:182

[03-Mar-2015 15:48:43 UTC] PHP   4. call_user_func(*uninitialized*, *uninitialized*, *uninitialized*) D:\web-site-dev\pyebrook.com\wp-admin\includes\template.php:1044

[03-Mar-2015 15:48:43 UTC] PHP   5. wpsc_dashboard_news(*uninitialized*, *uninitialized*) D:\web-site-dev\pyebrook.com\wp-admin\includes\template.php:1044

[03-Mar-2015 15:48:43 UTC] PHP   6. fetch_feed($url = *uninitialized*) D:\web-site-dev\pyebrook.com\wp-content\plugins\wp-e-commerce\wpsc-admin\admin.php:914

[03-Mar-2015 15:48:43 UTC] PHP   7. SimplePie->init() D:\web-site-dev\pyebrook.com\wp-includes\feed.php:644

[03-Mar-2015 15:48:43 UTC] PHP   8. SimplePie_Registry->call($type = *uninitialized*, $method = *uninitialized*, $parameters = *uninitialized*) D:\web-site-dev\pyebrook.com\wp-includes\class-simplepie.php:1338

[03-Mar-2015 15:48:43 UTC] PHP   9. call_user_func_array(*uninitialized*, *uninitialized*) D:\web-site-dev\pyebrook.com\wp-includes\SimplePie\Registry.php:215


```

**Comment by JeffPyeBrook** [comment] 2015-03-03 16:06
This is a little function people can drop int a .php file in their mu-plugins directory to work around the issue, or they can stop using the WP-eCommerce dashboard widget. It turns off the feed cache for the news feed.

I wouldn't recommend making this a permanent fix because (1) it is too hokey and (2) the feed cache is there for a reason, disabling it across 50,000 or more sites could have an adverse performance impact on the feed server


```

function hide_wpsc_dashboard_news_feed_error( &$feed, $url ) {

	if ( false !== strpos( $url, 'wpecommerce.org/feed/?category_name=news' ) ) {
		$feed->cache = false;
		remove_filter( 'wp_feed_options', __FUNCTION__, 10 );
	}
}

add_filter( 'wp_feed_options', 'hide_wpsc_dashboard_news_feed_error', 10, 2 );
```

**Comment by codesman** [comment] 2015-04-24 20:13
This does not appear to be a bug that is caused by WP-eCommerce News Dashboard Widget.  It is apparently a core bug as it occurs on the WordPress News widget in the Dashboard in a clean install of WordPress 4.2 and TwentyFifteen.

**Comment by JustinSainton** [comment] 2015-06-12 06:14
Thanks for the feedback, @codesman.  Closing as invalid.

**Closed by JustinSainton** 2015-06-12 06:14 UTC
